### ISSUE TITLE
PyPI improvements

### ISSUE THREAD

**Issue by yegorich** [adafruit/Adafruit_Python_ADS1x15#9]
While adding this package to Buildroot I've encountered following issues:

- package name in [JSON file](https://pypi.python.org/pypi/Adafruit-ADS1x15/json) is not the same as in [setup.py](https://github.com/adafruit/Adafruit_Python_ADS1x15/blob/master/setup.py#L20), i.e. **Adafruit-ADS1x15** vs **Adafruit_ADS1x15**

- LICENSE file is missing in the PyPI tarball

The same is true for Adafruit_Python_GPIO package.

**Comment by caternuson** [comment]
Hi! We are deprecating this library. This issue is either fixed or may need updating for the new library:
https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15

Please see issue summary here:
https://github.com/adafruit/Adafruit_Python_ADS1x15/issues/13
